# Generated by Django 4.1.3 on 2023-06-02 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_add_to_car_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_car_request',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
