# Generated by Django 4.1.3 on 2023-06-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_cart_created_at_remove_cart_product_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='from_user',
            new_name='user',
        ),
    ]
