# Generated by Django 4.1.3 on 2023-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_itemz',
            name='product_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
