# Generated by Django 4.1.3 on 2023-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_order_itemz_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_itemz',
            name='product_qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
