# Generated by Django 4.1.3 on 2023-06-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_order_itemz_product_qty_cart_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
