# Generated by Django 4.1.3 on 2023-06-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Pending', 'Pending'), ('Reject', 'Reject')], max_length=255, null=True),
        ),
    ]
