# Generated by Django 4.1.3 on 2023-06-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='price',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('Default', 'Default'), ('User_Fllow', 'User_Fllow'), ('User_Fllowing', 'User_Fllowing'), ('User_Post_like', 'User_Post_like'), ('User_New_Post', 'User_New_Post'), ('User_Post_Reviwes', 'User_Post_Reviwes'), ('User_Post_Reviwes_Replay', 'User_Post_Reviwes_Replay'), ('Page_Invitions_To_User', 'Page_Invitions_To_User'), ('User_Accept_userpage_Invitions', 'User_Accept_userpage_Invitions'), ('User_Accept_Page_Invitions', 'User_Accept_Page_Invitions'), ('User_Page_Join_Request', 'User_Page_Join_Request'), ('Page_Accept_User_Invitions', 'Page_Accept_User_Invitions'), ('Page_New_Post', 'Page_New_Post'), ('Intrest_Post_Reviwes', 'Intrest_Post_Reviwes'), ('Intrest_Post_Reviwes_Replay', 'Intrest_Post_Reviwes_Replay'), ('Intrest_level_2_Post_Reviwes', 'Intrest_level_2_Post_Reviwes'), ('Intrest_level_2_Post_Reviwes_Replay', 'Intrest_level_2_Post_Reviwes_Replay')], default='Default', max_length=150),
        ),
    ]
