# Generated by Django 4.1.3 on 2023-06-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_sell_category_remove_sell_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_qty',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
